### PR TITLE
Add the possibility to customize the remote user header name

### PR DESCRIPTION
**Pull request by skuzzle**
Inspired by the discussion [here](https://github.com/jonaswinkler/paperless-ng/discussions/639#discussion-3242017) it is worthwhile to be able to customize the header name that is used for authentication as its name is not really standardized.

### CODE REVIEW

**Comment by jonaswinkler** [comment]
Well yes, that's pretty much it.

**Comment by skuzzle** [comment]
I weren't able to actually test this yet because my local dev setup seems to be incomplete. I'll work on this. Still it would be great to have a unit test for this. Are there some authentication related tests that I can extend? I haven't found any and I don't feel competent enough to craft one from scratch.

Also, can you tell me what's up with this `Ansible Role / test (pull_request)` task that is failing?

**Comment by jonaswinkler** [comment]
> I weren't able to actually test this yet because my local dev setup seems to be incomplete.

What part seems incomplete? If something is giving you trouble, I might need to add that to the documentation.

> Still it would be great to have a unit test for this. Are there some authentication related tests that I can extend? I haven't found any and I don't feel competent enough to craft one from scratch.

I'll make something tonight. Although, pretty much everything authentication related is just standard django configuration, and these components are thoroughly tested.

> Also, can you tell me what's up with this `Ansible Role / test (pull_request)` task that is failing?

That's done by @C0nsultant and I believe that I didn't yet merge some of his changes on master into the dev branch.

**Comment by skuzzle** [comment]
I was thinking about a unit test that proves that the remote user stuff is only actually enabled when the respective properties are set. So that you'd find out if someone accidently flips the default behavior or something like that.

Regarding the local setup:
I haven't followed the configured steps thoroughly. I only went so far to install python so I could at least run the test. I was hoping I could simply build a docker container with my changes to test them, but that failed for reasons I do not understand:

```
\paperless-ng> docker build -t paperless-ng .
[...]
 => [stage-1  1/13] FROM docker.io/library/python:3.7-slim                                                         0.7s
 => => resolve docker.io/library/python:3.7-slim                                                                   0.0s
 => [jbig2enc 2/6] WORKDIR /usr/src/jbig2enc                                                                       0.1s
 => [stage-1  2/13] RUN apt-get update   && apt-get -y --no-install-recommends install   curl   file   fonts-lib  63.8s
 => [jbig2enc 3/6] RUN apt-get update && apt-get install -y --no-install-recommends build-essential automake lib  65.2s
 => [jbig2enc 4/6] RUN git clone https://github.com/agl/jbig2enc .                                                 1.7s
 => [jbig2enc 5/6] RUN ./autogen.sh                                                                                3.2s
 => [jbig2enc 6/6] RUN ./configure && make                                                                        15.1s
 => [stage-1  3/13] COPY --from=jbig2enc /usr/src/jbig2enc/src/.libs/libjbig2enc* /usr/local/lib/                  0.1s
 => [stage-1  4/13] COPY --from=jbig2enc /usr/src/jbig2enc/src/jbig2 /usr/local/bin/                               0.1s
 => [stage-1  5/13] COPY --from=jbig2enc /usr/src/jbig2enc/src/*.h /usr/local/include/                             0.1s
 => [stage-1  6/13] WORKDIR /usr/src/paperless/src/                                                                0.1s
 => [stage-1  7/13] COPY requirements.txt ../                                                                      0.1s
 => [stage-1  8/13] RUN apt-get update   && apt-get -y --no-install-recommends install   build-essential   libpq  80.8s
 => [stage-1  9/13] COPY docker/ ./docker/                                                                         0.1s
 => ERROR [stage-1 10/13] RUN cd docker   && cp imagemagick-policy.xml /etc/ImageMagick-6/policy.xml  && mkdir /v  0.5s
------
 > [stage-1 10/13] RUN cd docker   && cp imagemagick-policy.xml /etc/ImageMagick-6/policy.xml   && mkdir /var/log/supervisord /var/run/supervisord      && cp supervisord.conf /etc/supervisord.conf    && cp docker-entrypoint.sh /sbin/docker-entrypoint.sh   && chmod 755 /sbin/docker-entrypoint.sh         && chmod +x install_management_commands.sh      && ./install_management_commands.sh     && cd ..        && rm docker -rf:
#22 0.476 ./install_management_commands.sh: 1: ./install_management_commands.sh: Syntax error: word unexpected (expecting "do")
------
executor failed running [/bin/sh -c cd docker   && cp imagemagick-policy.xml /etc/ImageMagick-6/policy.xml      && mkdir /var/log/supervisord /var/run/supervisord      && cp supervisord.conf /etc/supervisord.conf    && cp docker-entrypoint.sh /sbin/docker-entrypoint.sh   && chmod 755 /sbin/docker-entrypoint.sh         && chmod +x install_management_commands.sh      && ./install_management_commands.sh     && cd ..        && rm docker -rf]: exit code: 2
```
Not sure wether this is a windows issue or something.

**Comment by jonaswinkler** [comment]
Oh. That's Windows CRLF line endings. Make sure that your git client does not convert linux line endings to windows line endings when checking out source code. Executing `install_management_commands.sh` in a linux environment with CRLF endings won't work.

I know that TortoiseSVN does these things, it's pretty annoying.

**Comment by skuzzle** [comment]
Ahh, good old windows line breaks...
I've now been able to build the docker image and to test it locally:
With `GET http://localhost:8000` I get a redirect to the login page, but when I include `X-Forwarded-User` I get the 200 response and a session id.

**Comment by jonaswinkler** [comment]
Oh wow, this actually worked. Never added some commits to a PR before.

**Comment by jonaswinkler** [comment]
This is really odd. These tests work locally, but not on Github actions.

**Comment by C0nsultant** [comment]
> > Also, can you tell me what's up with this `Ansible Role / test (pull_request)` task that is failing?
> 
> That's done by @C0nsultant and I believe that I didn't yet merge some of his changes on master into the dev branch.

Sorry, that is my bad. This is fixed in https://github.com/jonaswinkler/paperless-ng/commit/8f1e95a0ceddb5296d4c9fbc102a4c91b85757d7, which is only on `master` but not on `dev` (yet).

**Comment by jonaswinkler** [comment]
Alright. I've got no idea how to properly test that.

* when importing the django `TestCase` class and the http test client, the application gets loaded, `settings.py` gets executed, which ads the authentication classes if configured.
* Furthermore, the `header` value is set from setttings during import.
* Before the test even starts, everything is already configured, and `@override_settings` does not have any effect on that.
* I'd essentially have to set `header` on the authentication class by myself in the test case, and at this point I'm pretty much testing the `HttpRemoteUserMiddleware`, which is already done by django.

**Comment by skuzzle** [comment]
I have just a quick follow up question for which I don't want to create a new issue for now. I just tried to build a local image with my changes and run it on my production setup. From whatever version I build the image, I always run into the problem that the browser won't load the `js` files because of 
```
Die Ressource von "[redacted]/static/frontend/de/main.js" wurde wegen eines MIME-Typ-Konfliktes ("text/html") blockiert (X-Content-Type-Options: nosniff).
``` 
(Sorry for the german error message)

I just did `docker build -t blabla .` in the project's root directory and I tried it on `master` branch, the unmodified `ng-1.2.1` tag and the `ng-1.2.1` tag including my changes. Do I need to pass some special options to the build or what is going on there? When I run the `jonaswinkler/paperless-ng:1.2.1` image everything works just fine.

**Comment by jonaswinkler** [comment]
Building the docker image requires building the front end first. There's a script for that in the project root (`compile-frontend.sh`). This will put the `.js` files in the correct place.

* This step is deliberately not part of the Docker image build, since doing so would result in GitHub Actions building the front end for all three supported architectures separately (=slow).

* I'll update the documentation regarding that.

**Comment by mwllgr** [comment]
+1 for OIDC - I am using Keycloak to authenticate my services and paperless is missing so far. Someone already kinda implemented it: https://ciphermenial.github.io/posts/adding-oauth-to-paperless/ Would really be nice to have this.

**EDIT:** Whoops - wanted to post this in paperless-ngx. Sorry.

**Pull request merged**
