### PR TITLE
Add --no-progress-bar option to commands

### PR DESCRIPTION
**Pull request by sbrunner**
The progress bar is relay not useful when we call the commands from a cron job.

### CODE REVIEW

**Comment by sbrunner** [comment]
I don't understand the error on Ansible CI Is it related to my changes?

**Comment by jonaswinkler** [comment]
Hey @C0nsultant, If I recall correctly you're still generating random files for testing document upload?

https://github.com/jonaswinkler/paperless-ng/pull/934/checks?check_run_id=2374510698#step:7:1531

Seems like it managed to create a `image/jp2` file this time, whatever that is 😃 

@sbrunner Don't worry about that.

**Comment by jonaswinkler** [comment]
Sounds useful! Please merge into the dev branch.

**Comment by sbrunner** [comment]
Done :-)

**Comment by sbrunner** [comment]
Thanks :-)

**Comment by jonaswinkler** [comment]
A bit late, I know. If you get the conflict sorted in the other PR I'll merge that as well.

Also, I've seen your scan to paperless project. There's a section about affiliated projects in the readme. If you like, you can add that there as well, with a short description.

**Comment by sbrunner** [comment]
+1 I will do some updates in the project, then I will add it, thanks :-)

**Pull request merged**
