### PR TITLE
Suppport search term PDF open parameter

### PR DESCRIPTION
**Pull request by shamoon**
This PR addresses #858 and adds support for including a search term e.g. `#search=searchterm` in PDF previews for both search results pages as well as filtering

Screen Shot 2021-04-03 at 11 40 01 AM

Screen Shot 2021-04-03 at 1 13 24 PM

### CODE REVIEW

**Comment by jonaswinkler** [comment]
Well, thanks!

This is just for filtering by title (and content), right?

I'm pretty close to merging https://github.com/jonaswinkler/paperless-ng/tree/feature-unified-search, and that might affect a couple things here. That's full text search and more like this integrated with the existing document list + filtering and bulk editing.

**Comment by shamoon** [comment]
> I'm pretty close to merging https://github.com/jonaswinkler/paperless-ng/tree/feature-unified-search, and that might affect a couple things here. That's full text search and more like this integrated with the existing document list + filtering and bulk editing.

Your call, of course, I think this will be pretty easy to update, its really pretty straightforward, it just pulls in the search string from the query params or the search string is set from the filter editor. You can either merge that into dev and I'll update this after or merge it now and I can fix it if need be afterwards.

**Comment by shamoon** [comment]
@jonaswinkler I saw you merged the unified search into dev (awesome!) so I updated this to work with that, should be good to go.

**Comment by jonaswinkler** [comment]
This just got so much simpler. Great.

**Pull request merged**
