### PR TITLE
Refactored bulk editor

### PR DESCRIPTION
**Pull request by shamoon**
This PR addresses refactoring as discussed in https://github.com/jonaswinkler/paperless-ng/pull/162#issuecomment-750425915 , specifically `BulkEditor` now injects `DocumentListViewService` directly and performs operations without passing events to `DocumentList` component

### CODE REVIEW

**Comment by jonaswinkler** [comment]
Alright, this took longer than expected, but the outcome is solid. Here are a couple takeaways.

- Don't do complex logic in getters that you bind in angular templates. These are evaluated multiple times. The methods that built the list of ToggleableItems for the bulk edit drop downs was the cause of the performance issues. All three were getting called multiple times when making selection changes.
- Binding variables in SVG image urls is pretty slow and I don't know why.
- Regarding the filterable drop down component. I've changed lots of code so that only the drop down component is responsible for managing selection state. This removes lots of redundancy.

**Comment by shamoon** [comment]
Awesome work. Good to know about getters/svgs, sometimes I forget JS is not the speediest language... =)

**Comment by jonaswinkler** [comment]
It's very weird how some of the SVGs just pop in later and some appear instantly.

**Comment by shamoon** [comment]
You removed the apply on close, eh? I grew to find it incredibly useful, one less click and ok IMHO since theres a confirm. But of course, your call obviously.

**Comment by jonaswinkler** [comment]
Actually, I think I'm going to throw in some configuration options in the settings for that.

**Comment by shamoon** [comment]
Ha, nice.

**Comment by jonaswinkler** [comment]
Since you apparently already gave this a test run, everything working as before / as expected or did I miss something?

**Comment by shamoon** [comment]
Hmm, I think this broke the toggle functionality? So like if I select 3 documents I dont see their tags / correspondents / dts with  – / ✓ ? Screenshot below, in this example all 3 have tag "Inbox", 2 have "Test tag".

Screen Shot 2020-12-28 at 1 01 40 PM

Screen Shot 2020-12-28 at 1 01 07 PM

**Comment by jonaswinkler** [comment]
You need the back end running for that to work.

**Comment by shamoon** [comment]
Ah thought that might be the case. Well then I can’t fully test but certainly looks good

**Comment by jonaswinkler** [comment]
Apply on close is great with no confirmation dialogs. I've also sorted the drop downs by selection state, then name, so that (partially) selected items will always show on top. Pretty fast editing.

**Comment by shamoon** [comment]
Yea its pretty great–bravo!

**Pull request merged**
