### PR TITLE
FEATURE: create superuser in init script

### PR DESCRIPTION
**Pull request by bpereto**
create superuser in entrypoint script.

* Specifify `PAPERLESS_ADMIN_PASSWORD` which will be set every time the container starts.
* Specify `PAPERLESS_ADMIN_USER` for an alternative username. defaults to admin.

necessary functionality in a kubernetes environment.

### CODE REVIEW

**Comment by jonaswinkler** [comment]
Why is this required in a kubernetes environment? What prevents you from running the createsuperuser command?

**Comment by bpereto** [comment]
> Why is this required in a kubernetes environment? What prevents you from running the createsuperuser command?

yes, you can execute manually `createsuperuser` in the pod/container.

A common pattern in kubernetes deployment is to specify all the needed configurations as environment variables or secrets. with the deployment, you can generate a random secret for the admin/superuser account.
I will open a merge request with a helm chart for the deployment. It is not quite ready yet.

What opposes this approach?

**Comment by kbruegge** [comment]
I like the option of having a user/password  set using environment variables. I think its handy for docker compose stacks as well. :+1:

**Comment by jonaswinkler** [comment]
Alright. I really haven't used docker all that much before this project, and wasn't sure about this. Many images actually do this, so lets have this in paperless as well. Sorry for not really looking into this earlier.

However:

* I don't exactly like mixing python and bash code. That's impossible to test with unit tests, and I feel I want to get features tested that deal with authentication and user accounts.
* IIRC `dbshell` requires certain client programs for sqlite / postgres, and these are not installed in the image to save space.
* `createsuperuser` also has a non-interactive mode - can we use that?
* If not, a management command that gets called from the startup script would be much more approriate.
* Some documentation. There's a section about docker-specific variables, and this needs to be there.

**Comment by what-name** [comment]
I would like to deploy paperless-ng on AWS in ECS. This functionality is required for that as well. The `createsuperuser` can not be specified as the default command [in the docker-compose.yml] because in case the webserver container gets restarted, it will keep erroring out due to an already existing superuser. I believe there might be a way to make it work in that environment with the current `entrypoint.sh` but being able to specify the superuser username and password via env variables would be a great solution.

I have tested the PR and as @jonaswinkler said, neither `sqlite3` nor `psql` is present in the PATH inside the container. The following check
```
SUPERUSER_EXISTS=$(echo "SELECT * from auth_user;" | python3 manage.py dbshell | grep "${PAPERLESS_ADMIN_USER:=admin}")
```
throws an error `CommandError: You appear not to have the 'sqlite3' program installed or on your path.` or `psql` in case of postgres. The `SUPERUSER_EXISTS` variable will be left empty. This means that in case the `webserver` container does get restarted, it is not able to check if the superuser already exists and throws the following error [since the username does already exist].
```
sqlite3.IntegrityError: UNIQUE constraint failed: auth_user.username
```

I have tried to modify the PR's init script to use `manage.py` to check if the user already exists, to no avail [unfortunately my bash skills are a bit lacking].

**Comment by jonaswinkler** [comment]
This should ideally be a new management command (that reads environment variables and creates users / updates passwords as required), and the entrypoint script should simply call that.

**Comment by bpereto** [comment]
I will rework the pull request.

If the already existing createsuperuser command supports unattended adding/overwriting, we can use this.
Alternative is using a custom management command to realise this feature.

**Comment by jonaswinkler** [comment]
relevant

https://github.com/what-name/paperless-ng/commit/e3ba968fef1c9c1057cae68cf6f6a18cf7a1936c

**Comment by jonaswinkler** [comment]
@what-name Would you like to contribute your change back to the main repo? This would just need some documentation.

**Pull request closed without merging**
