### PR TITLE
Gunicorn should bind to both ipv4 and ipv6

### PR DESCRIPTION
**Pull request by growse**
As per https://docs.gunicorn.org/en/stable/settings.html#bind

### CODE REVIEW

**Comment by jonaswinkler** [comment]
Could we also put this into the `gunicorn.conf.py`? would be nicer this way, since that contains all the other config options as well.

**Comment by C0nsultant** [comment]
How would this work on systems that do not have IPv6 connectivity? Does it fall back to IPV4?
Default docker installation on Debian 10 provides no IPv6 out-of-the box (not even for `lo`).

```
root@host:~# docker run -it debian:10
root@778c4081c34f:/# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
236: eth0@if237: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:11:00:04 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.17.0.2/16 brd 172.17.255.255 scope global eth0
       valid_lft forever preferred_lft forever
```

**Comment by jonaswinkler** [comment]
apparently you can bind gunicorn to both IPv4 and IPv6.

**Comment by growse** [comment]
Binding to `[::]` seems to work quite happily on an ipv4-only host:

```
root@bd01dc0c73c8:/tmp# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
3: ip6tnl0@NONE: <NOARP> mtu 1452 qdisc noop state DOWN group default qlen 1000
    link/tunnel6 :: brd ::
6: eth0@if7: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:ac:11:00:02 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.17.0.2/16 brd 172.17.255.255 scope global eth0
       valid_lft forever preferred_lft forever
root@bd01dc0c73c8:/tmp# gunicorn3 -b '[::]:8000' myapp:app
[2020-12-29 11:42:12 +0000] [787] [INFO] Starting gunicorn 19.9.0
[2020-12-29 11:42:12 +0000] [787] [INFO] Listening at: http://[::]:8000 (787)
[2020-12-29 11:42:12 +0000] [787] [INFO] Using worker: sync
[2020-12-29 11:42:12 +0000] [790] [INFO] Booting worker with pid: 790
```

**Comment by C0nsultant** [comment]
Coming back to this... why should guinicorn inside of docker (where no IPv6 is available anyway) bind to all avaible IPv6 addresses?

**Pull request merged**
