### PR TITLE
Feature: popover document previews

### LINKED ISSUE #487: [Feature Request] Pop-out modal to preview documents from search / view
I am often checking a number of similar documents (from the thumbnail view) to find the correct one in a search query. This means clicking on the "edit" or "open in browser" button, then on the back button if it's not the one I was searching.

This causes a number of first-world-issues (that may or may not need fixing too), such as:

- extra page loads
- forgetting which results-page I was on when going back
- forgetting already-selected documents

I solve this by middle-clicking the preview button to open in new tabs. It also somewhat breaks immersion (for what that's worth) by opening the PDF in full view (in the browser).

I would like a way to open previews (the full PDF is okay) in a modal-style popup, which pops (partially, but mostly) over the current view / search results. Perhaps it can have "next" / "previous" links to show the next / previous document in the list.

A quick search brought this (using Bootstrap): http://dotnetqueries.com/Article/162/how-to-display-pdf-in-bootstrap-modal-popup

### PR DESCRIPTION
**Pull request by shamoon**
This PR implements popover previews as discussed and potentially closes #487 it:

- Adds a popup preview for documents that starts loading the file immediately on hover of the preview button but delays the preview display by 600ms to prevent annoyingness. Clicking preview button is preserved.
- Popovers can be interacted with but hide automatically on mouse out
- Removes ng2-pdf-viewer in favor of a workaround for the Safari crashing issue (see https://github.com/jonaswinkler/paperless-ng/issues/65#issuecomment-778433328 ) to maximize popover speed

Video:

https://user-images.githubusercontent.com/4887959/109066649-3885bb80-76a2-11eb-9388-2c18c677b190.mov

### CODE REVIEW

**Comment by jonaswinkler** [comment]
These videos are really handy! Sadly, this one does not seem to load.

**Comment by shamoon** [comment]
Well thats odd. How about this one?


https://user-images.githubusercontent.com/4887959/109072543-04ae9400-76aa-11eb-8f96-a34557a9deea.mov

**Comment by jonaswinkler** [comment]
Although this isn't exactly what I thought of in #487, this is really nice nonetheless.

image

Can we get rid of at least one of those scroll bars? :)

I think making this just a tad wider wouldn't hurt.

I'll take care of the merge conflicts.

**Comment by shamoon** [comment]
Cool, glad you like it too!

Im not seeing that double-scrollbar on my end, I'll see if I can reproduce but I have some ideas how to prevent with just CSS. I'll push some commits for that and I have an idea for the tooltip =) Should have some time later tonight

**Comment by shamoon** [comment]
Should all be sorted, tell me if I missed anything. 

I still cant reproduce the double scrollbars (I bet its browser/platform specific) but I think I found the source, LMK if not. Also made it a touch wider (someone suggested an option to set preview size, seems unnecessary but yea). Good point about the tooltip, I experimented with adding a [bootstrap tooltip](https://ng-bootstrap.github.io/#/components/tooltip/examples) but it seemed overkill so I just simplified the native tooltip to say "Click to view in browser", the idea being if the user is still hovering by the time the tooltip shows up they will a) have already seen the popover preview but now b) they know they can also click in case they didn't realize that =)

**Comment by jonaswinkler** [comment]
Had to revert this due to the calls to the metadata endpoint. Making API calls for every card slows down the document list drastically.

**Comment by shamoon** [comment]
I didn't notice any slowness here. Any thoughts on a solution? We could just leave the `type` attribute off the `<object>` tag, that seems to work fine in my testing and thats the only thing we use it for.

Otherwise a less expensive way to get it from the API?

**Comment by shamoon** [comment]
Yea, [Type is not required since data is specified](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/object#attributes)

**Comment by shamoon** [comment]
Can I push a commit with that change so you can test or do you have another solution in mind?

**Comment by jonaswinkler** [comment]
Sure. I think it's fine as long as you don't call the metadata endpoint. Just watch the server process 100 calls to that when loading a full page of documents or switching pages. Big no-go.

**Comment by shamoon** [comment]
Yes my bad, for sure 100 calls no-no. This makes me realize my dev install doesnt have enough documents.

Yes works for pdfs and text files! Screenshots attached

Should I make a new PR?

Screen Shot 2021-03-06 at 2 33 21 PM

Screen Shot 2021-03-06 at 2 32 20 PM

**Comment by jonaswinkler** [comment]
Uhm yes. I hope this works with the reverted commit on the dev branch.

**Comment by shamoon** [comment]
> Uhm yes. I hope this works with the reverted commit on the dev branch.

Ok a bit weird but I think new PR is good, LMK if any issue of course...

**Pull request merged**
