### PR TITLE
Add apple-touch-icon for iOS devices "Add to Home Screen"

### PR DESCRIPTION
**Pull request by joelnordell**
When installing paperless-ng to an iOS device as a PWA using "Add to Home Screen" this gives it a nicer icon.

See screenshot -- without this change, it looks like the one on the left. With this, it's the one on the right.

PNG image

### CODE REVIEW

**Comment by jonaswinkler** [comment]
Thank you! Could you please change the branch to `jonaswinkler:dev`?

**Comment by joelnordell** [comment]
Certainly - will do.

**Comment by joelnordell** [comment]
One quick note to be aware of -- I was not able to test this change in a built docker image, so I don't 100% know if it works properly in production mode; but it did work using the frontend's dev server (`ng serve`).

**Comment by jonaswinkler** [comment]
Well yes, in order for this to work, https://github.com/jonaswinkler/paperless-ng/blob/master/src/documents/templates/index.html needs adjustments, as well as the django view that serves this page.  The index.html you edited is only used with the development server.

I'll do that later, I already know exactly what to do.

**Comment by joelnordell** [comment]
Ah, perfect, thank you. I had a sneaking suspicion I was missing something.

**Comment by joelnordell** [comment]
@jonaswinkler -- here's the Inkscape SVG file I used to create the PNG icon, in case you'd also like to add that to the repo or otherwise keep it somewhere else. I started from the `paperless-logo-white-notext.svg` file, and added the green background layer and also added a copy of the iOS style-guideline icon grid in a (hidden) layer for reference.

(Zipped because Github doesn't support uploading an SVG directly)

[paperless-logo-apple-touch-icon.zip](https://github.com/jonaswinkler/paperless-ng/files/6029971/paperless-logo-apple-touch-icon.zip)

**Comment by jonaswinkler** [comment]
@joelnordell 

`<link ref="apple-touch-icon" href="apple-touch-icon.png">`

I assume that `ref=` is a typo and changed that to `rel=`. My IDE complained about that. Or is this intentional?

Also, please report back if this works as soon as 1.2.1 is out.

**Comment by joelnordell** [comment]
@jonaswinkler oh yes indeed that was a typo - good catch! (d'oh) I'm actually surprised that the icon still worked in my testing with the dev server, despite that typo.

Will for sure report back after updating to 1.2.1, thanks.

**Comment by joelnordell** [comment]
@jonaswinkler -- following up here, I've just updated to 1.2.1 and while I do see the `<link rel="apple-touch-icon" href="apple-touch-icon.png">` tag, the actual icon itself doesn't load:

* Should the href be `/apple-touch-icon.png` (as an absolute rather than relative path) -- though maybe it is actually correct since the dashboard path is just `/dashboard` without a trailing slash. And, a relative path is better for proxying anyway.

* The real problem, I'm fairly sure, is that `http://paperless-server/apple-touch-icon.png` produces a `404 not found` error.

**Comment by joelnordell** [comment]
Going inside the docker image, I do see the `apple-touch-icon.png` file _seemingly_ in the right places? (Though I don't really know what the layout is supposed to be for the webserver.)

image

**Comment by jonaswinkler** [comment]
My bad, I totally messed that up. Fixed.

**Comment by joelnordell** [comment]
ha - you're too fast -- I had just made that exact same fix myself and was about to submit a new PR :)

**Comment by joelnordell** [comment]
This brings to mind a thought though -- since `apple-touch-icon.png` is the exact same file in all languages, does it actually need to be copied in all the language-specific directories, or can it just exist once somewhere, like just in `static`?

**Comment by jonaswinkler** [comment]
This sadly is the way Angular handles assets, and deployment in general. Angular generates a complete package for every locale, and the server selects the correct one based on cookies and browser settings. Apparently because assets may have localized versions as well.

However... we might not need to put this in the source of the angular project folder at all.

**Comment by joelnordell** [comment]
Interesting. I didn't realize Angular was so all-encompassing. I haven't worked with it before -- only React and Vue, both of which have more of a "I'm just a view library" attitude and leave things like build & deployment up to others.

I'm not worried too much about it, it's a small file, so what's a couple extra kilobytes of wasted disk space...

**Comment by joelnordell** [comment]
And actually, doesn't docker use squashfs to create images? It should de-duplicate those files anyway.

**Comment by joelnordell** [comment]
@jonaswinkler - following up on this

With version 1.3.0 the icon is working! 🎉 

image

**Pull request merged**
