### PR TITLE
Date dropdown clear buttons, keyboard support

### LINKED ISSUE #144: Adding date filters without the calendar popup doesn't work - also removing a date filter doesn't
What I did is enter a specific date and pushed Enter and clicked away the filter drop-down, nothing happened. I had to open the calendar-pop (wanted date was already selected), click the date again and it worked.

Also I couldn't find a way to remove one of the two date filters, I guess this is solved when the first part is solved. (of course removing all date filters and then set the wanted would work)

P.S.: Amazing progress!!

### PR DESCRIPTION
**Pull request by shamoon**
This PR closes #144 , it adds:

- Clear buttons for each date field (after / before)
- Allows date field searching using keyboard input
- Shows visual feedback if date entered with keyboard is invalid
- Executes search after 'Enter' key pressed
- Swaps position of after & before (because I realized if you think of a range like _From X to Y_ then "after" (X) comes first.

### CODE REVIEW

**Comment by jonaswinkler** [comment]
Thank you! I'll have a look at it later.

**Comment by jonaswinkler** [comment]
This doesn't really work. Well, it kind of does, but If I try to manually edit the year the cursor jumps back to the end and a request is made to the server, which results in a Bad Request 400. I'd rather much like the request to be made when I'm done typing.

Maybe we should try using the other date selection inputs, the one I've also used on the document editing form.

**Comment by shamoon** [comment]
Hmm, shouldn’t submit unless date is valid. Lemme look...

**Comment by jonaswinkler** [comment]
Or rather, until exiting the field (or pressing enter).

**Comment by shamoon** [comment]
Ok I think I sorted it all. Also added a little visual feedback if the keyboard input is not a valid date and made it only submit on 'Enter'

**Comment by jonaswinkler** [comment]
When I select a date with the quick filters, close the drop down, clear all filters with the rightmost button, the dates don't get properly cleared. Open up the drop down again, and the list view reloads with the filter active again. Very strange.

**Comment by shamoon** [comment]
Ok last commit should fix that hopefully.

**Comment by jonaswinkler** [comment]
Alright, I've replaced the ngbDatepicker with a regular <input type="date">, which works just as well for selecting dates. This thing also does not fire (change) events when the input is still incomplete. Debounce on that, works. Also, when passing around date strings (which is totally fine), the infinite loop you discovered does not trigger, so I was able to get rid of the hack.

That should wrap up this issue.

**Pull request closed without merging**
