### PR TITLE
Change PDF rendering

### LINKED ISSUE #65: Paperless-ng crashes webbrowser Safari (MacOS) when clicking the edit-icon
When I click the edit icon while using Safari, it seems that paperless-ng fully hangs, even a refresh of the site hangs/loads forever. Weird thing is, everything works fine in Edge of Chrome.

### PR DESCRIPTION
**Pull request by shamoon**
This PR closes #65 

I believe the issue is related to the `<object>` embed and / or the `sanitizer.bypassSecurityTrustResourceUrl` (not certain) but this solution uses an additional package [ng2-pdf-viewer](https://github.com/VadimDez/ng2-pdf-viewer) to render PDFs. Obviously its adding a dependency but besides fixing the fatal crash using this package also has advantages as PDF is actually rendered (e.g. not just displayed in iframe/object) so text is selectable, no plugin needed, etc. Screenshot attached (its styled to pretty much look the same! 😃):

Screen Shot 2020-12-11 at 2 20 33 PM

### CODE REVIEW

**Comment by jonaswinkler** [comment]
Wow, you're really getting into this. Thanks!

Maybe the performance issues I've been getting with the object tag will also be resolved with this. I'll check that out tomorrow.

**Comment by jonaswinkler** [comment]
I'm getting some layout issues with this.

image

Sometimes, when opening documents, the document display is way to big. This also always happens when resizing the window. Changing to the metadata tab in this state also puts the document preview below the left column and makes the left column full-width. Ideally, both columns would stay the same with, except on smaller screens, where the preview disappears.

**Comment by shamoon** [comment]
Should be easy to fix by explicating setting bootstrap columns, the renderer can get a little greedy with setting its size. I made it 50%/50% on medium screens, 33%/66% on very large screens (since form doesnt need to get so crazy wide). Attached screenshots

Screen Shot 2020-12-12 at 8 46 03 AM
Screen Shot 2020-12-12 at 8 45 57 AM

**Comment by jonaswinkler** [comment]
Splendit!

**Comment by jonaswinkler** [comment]
@shamoon 

Mobile support still got a long way to go, and so far, no one has raise any interest in that, but I'll ask anyway.

I'd like to provide the preview as an additional tab on smaller screens, instead of within a second column. Would you happen to know how to achieve that? The only way I can thing of right now would be to get the preview viewer in its own component, add it to both the tabs and as a column, and show/hide it using these breakpoint classes. Not sure if its possible/advised to magically move dom elements around, or something like that.

**Comment by shamoon** [comment]
Yea I think thats the way to do it basically with CSS, I'll submit a quick PR, works well IMHO

**Pull request merged**
