### PR TITLE
Feature: dark mode

### LINKED ISSUE #194: [Feature Request] Dark Theme
Hello,
is it possible to have a dark theme?
At night, white background is a little violent for the eyes :)

Thank you for the very good job.

### PR DESCRIPTION
**Pull request by shamoon**
This PR implements "dark mode" as discussed and closes #194

### CODE REVIEW

**Comment by jonaswinkler** [comment]
Awesome.

I've got a couple nitpicks.

image

Link texts should really be very bright, the list is very hard to read.

image

Weird coloring of tags on large cards. Links are white on here, for some reason. Oddly enough, tags in the search results look fine, and these use the same component.

image

Black text on the start page. This is displayed when no saved views are present.

image

I think there's a logo for dark screens as well, not sure.

image

Apart from the horrible thumbnail, there's a white line here that looks weird.

image

Dark link text is really hard to read.

image

Can we get the "X" in white?

image

The Cancel button looks like it's disabled. The Discard button on the document edit page looks fine.

image

Would be nice if the background of the score bars would also adjust.

Also: Try the ng-select drop downs, they kinda break with this. Only the layout, not the functionality. No content is displayed when focussed.

**Comment by shamoon** [comment]
I expect nothing less! 😀

I’ll sort these out probably later today

**Comment by jonaswinkler** [comment]
Also, I've noticed that the previews on large cards don't have a white background anymore, its now grey-ish, just like the rest of the card.

**Comment by shamoon** [comment]
Yea that seemed like more than I expected, I lost some changes for some reason but NBD I'll put it back

**Comment by shamoon** [comment]
Ok please take another look when you have a second, feedback welcome.

Regarding the `ng-select`s I was pretty certain that I had done them and they look OK to me, see screenshots. Are you seeing something else?

Screen Shot 2020-12-28 at 4 48 27 PM

Screen Shot 2020-12-28 at 4 37 29 PM

**Comment by jonaswinkler** [comment]
Well, the actual field (not the content of the drop down) appeared empty when focussed, even though something is selected.

**Comment by shamoon** [comment]
Oh I see! Ok 1 sec

**Comment by shamoon** [comment]
Sorted =)

**Comment by jonaswinkler** [comment]
I made a new settings service that makes dealing with configuration options much more easy. Could you please adjust this to use the new service?

**Comment by jonaswinkler** [comment]
See b2327d6fde161b0a22f245c795273f1689572361

**Comment by shamoon** [comment]
Ok this should be all set with new service, please check out and let me know if any issues.

**Comment by shamoon** [comment]
@jonaswinkler any issues with this? I know you’re busy, not urgent. I just want to make sure navbar changes #217 will be compatible etc once this is merged

**Comment by jonaswinkler** [comment]
Well, time is an issue :)

Looks good so far. Merged so that we can move on. Two minor nitpicks remain.

- The correspondent links on large cards appear as white, while all other links appear as green.
- I still think that link text should be as bright as normal text, especially for the tabular document list.

**Comment by shamoon** [comment]
Ha. Well clearly this project is really exciting to people but yea, I definitely realize **& appreciate** how much time you’re dedicating—I’m sure others do too!

Let me know if you want me to look at those two things you mentioned, I know you can do all of this yourself but as you said, time!

**Comment by jonaswinkler** [comment]
Please do that, you'll probably get this done much quicker than me.

**Comment by shamoon** [comment]
You're right about that! See PR #241

Leave you to do the hard stuff =)

**Pull request merged**
