### PR TITLE
Add option to ignore certain dates in parse_date

### PR DESCRIPTION
**Pull request by jayme-github**
PAPERLESS_IGNORE_DATES allows to specify a comma separated list of dates
to ignore during date parsing (from filename and content). This can be
used so specify dates that do appear often in documents but are usually
not the documents creation date (like your date of birth).

### CODE REVIEW

**Comment by jonaswinkler** [comment]
Looks good!

Could you also add some documentation and add the configuration option to `paperless.conf.example`?

**Comment by jayme-github** [comment]
Sure thing, thanks for taking a look!

**Comment by jonaswinkler** [comment]
Will test later, but this looks good so far.

**Comment by jonaswinkler** [comment]
Works like a charm.

**Pull request merged**
