### PR TITLE
docker-entrypoint.sh: don't crash on chown errors

### PR DESCRIPTION
**Pull request by sbrl**
This pull request adds a new environment variable (`PAPERLESS_NO_CHOWN`) to control whether paperless-ng tries to chown it's home directory.

If set to a non-empty string, it causes paperless-ng to skip chowning it's home directory.

This is required when using NFS, because you can't safely allow remote users to chown things on an NFS share (at least as far as I know).

### CODE REVIEW

**Comment by jonaswinkler** [comment]
Thank you!

a. Please add some documentation. There's a section about docker specific variables.
b. Also consider `set +e` and `set -e` around that, so that the entry point script does not exit when `chown` fails. I think that's much better than another config option.

**Comment by sbrl** [comment]
Oh, I like that alternative a lot! I've pushed another commit to do that instead. It's transparent, unlike my solution which required an extra environment variable.

**Comment by jonaswinkler** [comment]
Documentation: no.

Does this work for you this way? I can't verify it.

**Comment by sbrl** [comment]
Right, got it.

I've just done some testing, and the result is that yes, it does work, but there's more to be done. Namely, because the `flock` for the database migrations is run as root, it doesn't work. Specifically, it's `/usr/src/paperless/data/migration_lock` that it needs to write to, but can't. It's [this line](https://github.com/jonaswinkler/paperless-ng/blob/dev/docker/docker-entrypoint.sh#L67).

In theory if we moved the `sudo -HEu paperless` bit from inside the migrations to outside (where it's called by `initialize`), this would resolve the problem.

Does this sound like an acceptable change?

**Comment by sbrl** [comment]
Oh wait, you can't run the entire function as the `paperless` user because `sudo` clears the environment variable that allows it to pass the shell function as root.

Bother, I'm not sure how to crack this one.

**Comment by sbrl** [comment]
Got it, I think. This gets us as far as this:

```bash
Type 'manage.py help <subcommand>' for help on a specific subcommand.

Available subcommands:

....
```

Running `/sbin/docker-entrypoint.sh /usr/local/bin/supervisord -c /etc/supervisord.conf` in the Docker container now works as intended (except it crashes because I don't have a Redis container setup in my test environment - my Hashicorp Nomad and Hashicorp Consul system runs that).

**Comment by sbrl** [comment]
Conflicts resolved, @jonaswinkler. Thoughts on my fix? Or shall I try and think of a different solution to the problem?

**Comment by jonaswinkler** [comment]
Well, I' very relucant on this because I don't fully understand how the changed code works. It seems to work on my machine, but I don't want to accidentally break hundreds of other installations in case this has some undiscovered side effects.

**Comment by sbrl** [comment]
Ah, I see @jonaswinkler - clarity of code here is definitely important.

The problem that I needed to overcome here is that the `flock` in the database migrations function doesn't work when you're using NFS, because the `flock` runs as root and tries to write to the NFS share, which fails.

My solution here is to run the whole `migrations` function as the `paperless` user inside the docker container, but this is complicated by the fact that  `sudo -E` does _not_ in fact preserve all environment variables - it scrubs bash functions exported with `export -f`.

Perhaps an alternative solution here would be to put the miscellaneous startup tasks here in a separate file, and then run that with `sudo -HEu paperless` instead. This way we can avoid any potential issues or fragility associated with the complex `--preserve-env` directives I've used here.

What a new file alongside the `docker-entrypoint.sh` script called `docker-prestart.sh`?

Does this sound like a more acceptable solution? If not I'll go back to the drawing board and come up with something else.

**Comment by jonaswinkler** [comment]
> What a new file alongside the `docker-entrypoint.sh` script called `docker-prestart.sh`?

That sounds like a very good idea. Have `docker-entrypoint.sh` do everything for which root privileges are required, and then sudo the other script. I'll look at the code tomorrow and get back to you. Right now I need some sleep.

**Comment by sbrl** [comment]
Ok, sure thing! Sounds good :slightly_smiling_face:

**Comment by jonaswinkler** [comment]
Alright, lets do it like you proposed, lets have an additional script `docker-prepare.sh` that does everything that needs to run as the paperless user. Would you like to take care of that?

**Comment by sbrl** [comment]
Sure thing, I'll take care of it. This PR might go wonky for a moment while I rebase etc.

**Comment by sbrl** [comment]
No, GitHub! You have got very confused indeed. I did NOT ask you to close this.....

**Comment by sbrl** [comment]
Right, I've rebased against the `dev` branch and deleted my earlier work, so now I'm ready to make the changes to split the existing `docker-entrypoint.sh` file in 2.

**Comment by sbrl** [comment]
Changes completed. Just building the Docker container to check that it actually works.

**Comment by sbrl** [comment]
I get this error when trying to build the Docker container for some strange reason @jonaswinkler:
```
Err:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
  At least one invalid signature was encountered.
Err:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
  At least one invalid signature was encountered.
Err:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
  At least one invalid signature was encountered.
Err:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
  At least one invalid signature was encountered.
Reading package lists...
W: GPG error: http://ports.ubuntu.com/ubuntu-ports focal InRelease: At least one invalid signature was encountered.
E: The repository 'http://ports.ubuntu.com/ubuntu-ports focal InRelease' is not signed.
W: GPG error: http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease: At least one invalid signature was encountered.
E: The repository 'http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease' is not signed.
W: GPG error: http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease: At least one invalid signature was encountered.
E: The repository 'http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease' is not signed.
W: GPG error: http://ports.ubuntu.com/ubuntu-ports focal-security InRelease: At least one invalid signature was encountered.
E: The repository 'http://ports.ubuntu.com/ubuntu-ports focal-security InRelease' is not signed.
```

**Comment by sbrl** [comment]
Oops, I missed some rogue `sudo` calls - fixed and rebuilding the Docker container again overnight for another test in the morning.

**Comment by sbrl** [comment]
Aaaand I forgot to `git pull` on the host in my cluster I'm rebuilding the docker container on, so I'm rebuilding again (it takes 1 hr+)

**Comment by sbrl** [comment]
Ok, I can confirm that this works now @jonaswinkler, this is ready for review.

**Comment by sbrl** [comment]
Thanks, @jonaswinkler :-)

**Pull request merged**
