### PR TITLE
Ansible - Fix uvicorn dependency issue for >1.0.0

### PR DESCRIPTION
**Pull request by C0nsultant**
Note that this is a very crude fix for your current development.
I would highly recommend using a more advanced version check than `version == '1.0.0'`.

### CODE REVIEW

**Comment by C0nsultant** [comment]
The problem is different this time around:

```
root@debianbuster:/# journalctl -u paperless-webserver
-- Logs begin at Sun 2021-01-31 09:34:02 UTC, end at Sun 2021-01-31 09:39:44 UTC. --
Jan 31 09:39:07 debianbuster systemd[1]: Started Paperless webserver.
Jan 31 09:39:07 debianbuster gunicorn[12015]: [2021-01-31 09:39:07 +0000] [12015] [INFO] Starting gunicorn 20.0.4
Jan 31 09:39:07 debianbuster gunicorn[12015]: [2021-01-31 09:39:07 +0000] [12015] [INFO] Listening at: http://127.0.0.1:8000 (12015)
Jan 31 09:39:07 debianbuster gunicorn[12015]: [2021-01-31 09:39:07 +0000] [12015] [INFO] Using worker: sync
Jan 31 09:39:07 debianbuster gunicorn[12015]: [2021-01-31 09:39:07 +0000] [12032] [INFO] Booting worker with pid: 12032
Jan 31 09:39:07 debianbuster gunicorn[12015]: [2021-01-31 09:39:07 +0000] [12033] [INFO] Booting worker with pid: 12033
Jan 31 09:39:07 debianbuster gunicorn[12015]: [2021-01-31 09:39:07 +0000] [12033] [ERROR] Exception in worker process
Jan 31 09:39:07 debianbuster gunicorn[12015]: Traceback (most recent call last):
Jan 31 09:39:07 debianbuster gunicorn[12015]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
Jan 31 09:39:07 debianbuster gunicorn[12015]:     worker.init_process()
Jan 31 09:39:07 debianbuster gunicorn[12015]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
Jan 31 09:39:07 debianbuster gunicorn[12015]:     self.load_wsgi()
Jan 31 09:39:07 debianbuster gunicorn[12015]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
Jan 31 09:39:07 debianbuster gunicorn[12015]:     self.wsgi = self.app.wsgi()
Jan 31 09:39:07 debianbuster gunicorn[12015]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
Jan 31 09:39:07 debianbuster gunicorn[12015]:     self.callable = self.load()
Jan 31 09:39:07 debianbuster gunicorn[12015]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
Jan 31 09:39:07 debianbuster gunicorn[12015]:     return self.load_wsgiapp()
Jan 31 09:39:07 debianbuster gunicorn[12015]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
Jan 31 09:39:07 debianbuster gunicorn[12015]:     return util.import_app(self.app_uri)
Jan 31 09:39:07 debianbuster gunicorn[12015]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
Jan 31 09:39:07 debianbuster gunicorn[12015]:     mod = importlib.import_module(module)
Jan 31 09:39:07 debianbuster gunicorn[12015]:   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
Jan 31 09:39:07 debianbuster gunicorn[12015]:     return _bootstrap._gcd_import(name[level:], package, level)
Jan 31 09:39:07 debianbuster gunicorn[12015]:   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
Jan 31 09:39:07 debianbuster gunicorn[12015]:   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
Jan 31 09:39:07 debianbuster gunicorn[12015]:   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
Jan 31 09:39:07 debianbuster gunicorn[12015]: ModuleNotFoundError: No module named 'paperless.asgi'
Jan 31 09:39:07 debianbuster gunicorn[12015]: [2021-01-31 09:39:07 +0000] [12032] [ERROR] Exception in worker process
Jan 31 09:39:07 debianbuster gunicorn[12015]: Traceback (most recent call last):
Jan 31 09:39:07 debianbuster gunicorn[12015]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
Jan 31 09:39:07 debianbuster gunicorn[12015]:     worker.init_process()
Jan 31 09:39:07 debianbuster gunicorn[12015]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
Jan 31 09:39:07 debianbuster gunicorn[12015]:     self.load_wsgi()
Jan 31 09:39:07 debianbuster gunicorn[12015]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
Jan 31 09:39:07 debianbuster gunicorn[12015]:     self.wsgi = self.app.wsgi()
Jan 31 09:39:07 debianbuster gunicorn[12015]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
Jan 31 09:39:07 debianbuster gunicorn[12015]:     self.callable = self.load()
Jan 31 09:39:07 debianbuster gunicorn[12015]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
Jan 31 09:39:07 debianbuster gunicorn[12015]:     return self.load_wsgiapp()
Jan 31 09:39:07 debianbuster gunicorn[12015]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
Jan 31 09:39:07 debianbuster gunicorn[12015]:     return util.import_app(self.app_uri)
Jan 31 09:39:07 debianbuster gunicorn[12015]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
Jan 31 09:39:07 debianbuster gunicorn[12015]:     mod = importlib.import_module(module)
Jan 31 09:39:07 debianbuster gunicorn[12015]:   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
Jan 31 09:39:07 debianbuster gunicorn[12015]:     return _bootstrap._gcd_import(name[level:], package, level)
Jan 31 09:39:07 debianbuster gunicorn[12015]:   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
Jan 31 09:39:07 debianbuster gunicorn[12015]:   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
Jan 31 09:39:07 debianbuster gunicorn[12015]:   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
Jan 31 09:39:07 debianbuster gunicorn[12015]: ModuleNotFoundError: No module named 'paperless.asgi'
Jan 31 09:39:07 debianbuster gunicorn[12015]: [2021-01-31 09:39:07 +0000] [12032] [INFO] Worker exiting (pid: 12032)
Jan 31 09:39:07 debianbuster gunicorn[12015]: [2021-01-31 09:39:07 +0000] [12033] [INFO] Worker exiting (pid: 12033)
Jan 31 09:39:08 debianbuster gunicorn[12015]: [2021-01-31 09:39:08 +0000] [12015] [INFO] Shutting down: Master
Jan 31 09:39:08 debianbuster gunicorn[12015]: [2021-01-31 09:39:08 +0000] [12015] [INFO] Reason: Worker failed to boot.
Jan 31 09:39:08 debianbuster systemd[1]: paperless-webserver.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Jan 31 09:39:08 debianbuster systemd[1]: paperless-webserver.service: Failed with result 'exit-code'.
Jan 31 09:39:12 debianbuster systemd[1]: Started Paperless webserver.
Jan 31 09:39:12 debianbuster gunicorn[12243]: [2021-01-31 09:39:12 +0000] [12243] [INFO] Starting gunicorn 20.0.4
Jan 31 09:39:12 debianbuster gunicorn[12243]: [2021-01-31 09:39:12 +0000] [12243] [INFO] Listening at: http://127.0.0.1:8000 (12243)
Jan 31 09:39:12 debianbuster gunicorn[12243]: [2021-01-31 09:39:12 +0000] [12243] [INFO] Using worker: sync
Jan 31 09:39:12 debianbuster gunicorn[12243]: [2021-01-31 09:39:12 +0000] [12256] [INFO] Booting worker with pid: 12256
Jan 31 09:39:12 debianbuster gunicorn[12243]: [2021-01-31 09:39:12 +0000] [12257] [INFO] Booting worker with pid: 12257
Jan 31 09:39:12 debianbuster gunicorn[12243]: [2021-01-31 09:39:12 +0000] [12256] [ERROR] Exception in worker process
Jan 31 09:39:12 debianbuster gunicorn[12243]: Traceback (most recent call last):
Jan 31 09:39:12 debianbuster gunicorn[12243]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
Jan 31 09:39:12 debianbuster gunicorn[12243]:     worker.init_process()
Jan 31 09:39:12 debianbuster gunicorn[12243]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
Jan 31 09:39:12 debianbuster gunicorn[12243]:     self.load_wsgi()
Jan 31 09:39:12 debianbuster gunicorn[12243]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
Jan 31 09:39:12 debianbuster gunicorn[12243]:     self.wsgi = self.app.wsgi()
Jan 31 09:39:12 debianbuster gunicorn[12243]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
Jan 31 09:39:12 debianbuster gunicorn[12243]:     self.callable = self.load()
Jan 31 09:39:12 debianbuster gunicorn[12243]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
Jan 31 09:39:12 debianbuster gunicorn[12243]:     return self.load_wsgiapp()
Jan 31 09:39:12 debianbuster gunicorn[12243]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
Jan 31 09:39:12 debianbuster gunicorn[12243]:     return util.import_app(self.app_uri)
Jan 31 09:39:12 debianbuster gunicorn[12243]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
Jan 31 09:39:12 debianbuster gunicorn[12243]:     mod = importlib.import_module(module)
Jan 31 09:39:12 debianbuster gunicorn[12243]:   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
Jan 31 09:39:12 debianbuster gunicorn[12243]:     return _bootstrap._gcd_import(name[level:], package, level)
Jan 31 09:39:12 debianbuster gunicorn[12243]:   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
Jan 31 09:39:12 debianbuster gunicorn[12243]:   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
Jan 31 09:39:12 debianbuster gunicorn[12243]:   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
Jan 31 09:39:12 debianbuster gunicorn[12243]: ModuleNotFoundError: No module named 'paperless.asgi'
Jan 31 09:39:12 debianbuster gunicorn[12243]: [2021-01-31 09:39:12 +0000] [12256] [INFO] Worker exiting (pid: 12256)
Jan 31 09:39:13 debianbuster gunicorn[12243]: [2021-01-31 09:39:13 +0000] [12257] [ERROR] Exception in worker process
Jan 31 09:39:13 debianbuster gunicorn[12243]: Traceback (most recent call last):
Jan 31 09:39:13 debianbuster gunicorn[12243]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
Jan 31 09:39:13 debianbuster gunicorn[12243]:     worker.init_process()
Jan 31 09:39:13 debianbuster gunicorn[12243]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
Jan 31 09:39:13 debianbuster gunicorn[12243]:     self.load_wsgi()
Jan 31 09:39:13 debianbuster gunicorn[12243]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
Jan 31 09:39:13 debianbuster gunicorn[12243]:     self.wsgi = self.app.wsgi()
Jan 31 09:39:13 debianbuster gunicorn[12243]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
Jan 31 09:39:13 debianbuster gunicorn[12243]:     self.callable = self.load()
Jan 31 09:39:13 debianbuster gunicorn[12243]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
Jan 31 09:39:13 debianbuster gunicorn[12243]:     return self.load_wsgiapp()
Jan 31 09:39:13 debianbuster gunicorn[12243]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
Jan 31 09:39:13 debianbuster gunicorn[12243]:     return util.import_app(self.app_uri)
Jan 31 09:39:13 debianbuster gunicorn[12243]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
Jan 31 09:39:13 debianbuster gunicorn[12243]:     mod = importlib.import_module(module)
Jan 31 09:39:13 debianbuster gunicorn[12243]:   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
Jan 31 09:39:13 debianbuster gunicorn[12243]:     return _bootstrap._gcd_import(name[level:], package, level)
Jan 31 09:39:13 debianbuster gunicorn[12243]:   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
Jan 31 09:39:13 debianbuster gunicorn[12243]:   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
Jan 31 09:39:13 debianbuster gunicorn[12243]:   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
Jan 31 09:39:13 debianbuster gunicorn[12243]: ModuleNotFoundError: No module named 'paperless.asgi'
Jan 31 09:39:13 debianbuster gunicorn[12243]: [2021-01-31 09:39:13 +0000] [12257] [INFO] Worker exiting (pid: 12257)
Jan 31 09:39:13 debianbuster gunicorn[12243]: Traceback (most recent call last):
Jan 31 09:39:13 debianbuster gunicorn[12243]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 209, in run
Jan 31 09:39:13 debianbuster gunicorn[12243]:     self.sleep()
Jan 31 09:39:13 debianbuster gunicorn[12243]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 357, in sleep
Jan 31 09:39:13 debianbuster gunicorn[12243]:     ready = select.select([self.PIPE[0]], [], [], 1.0)
Jan 31 09:39:13 debianbuster gunicorn[12243]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
Jan 31 09:39:13 debianbuster gunicorn[12243]:     self.reap_workers()
Jan 31 09:39:13 debianbuster gunicorn[12243]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
Jan 31 09:39:13 debianbuster gunicorn[12243]:     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
Jan 31 09:39:13 debianbuster gunicorn[12243]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
Jan 31 09:39:13 debianbuster gunicorn[12243]: During handling of the above exception, another exception occurred:
Jan 31 09:39:13 debianbuster gunicorn[12243]: Traceback (most recent call last):
Jan 31 09:39:13 debianbuster gunicorn[12243]:   File "/opt/paperless-ng/.venv/bin/gunicorn", line 8, in <module>
Jan 31 09:39:13 debianbuster gunicorn[12243]:     sys.exit(run())
Jan 31 09:39:13 debianbuster gunicorn[12243]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in run
Jan 31 09:39:13 debianbuster gunicorn[12243]:     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
Jan 31 09:39:13 debianbuster gunicorn[12243]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/app/base.py", line 228, in run
Jan 31 09:39:13 debianbuster gunicorn[12243]:     super().run()
Jan 31 09:39:13 debianbuster gunicorn[12243]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/app/base.py", line 72, in run
Jan 31 09:39:13 debianbuster gunicorn[12243]:     Arbiter(self).run()
Jan 31 09:39:13 debianbuster gunicorn[12243]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 229, in run
Jan 31 09:39:13 debianbuster gunicorn[12243]:     self.halt(reason=inst.reason, exit_status=inst.exit_status)
Jan 31 09:39:13 debianbuster gunicorn[12243]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 342, in halt
Jan 31 09:39:13 debianbuster gunicorn[12243]:     self.stop()
Jan 31 09:39:13 debianbuster gunicorn[12243]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 393, in stop
Jan 31 09:39:13 debianbuster gunicorn[12243]:     time.sleep(0.1)
Jan 31 09:39:13 debianbuster gunicorn[12243]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
Jan 31 09:39:13 debianbuster gunicorn[12243]:     self.reap_workers()
Jan 31 09:39:13 debianbuster gunicorn[12243]:   File "/opt/paperless-ng/.venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
Jan 31 09:39:13 debianbuster gunicorn[12243]:     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
Jan 31 09:39:13 debianbuster gunicorn[12243]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
Jan 31 09:39:13 debianbuster systemd[1]: paperless-webserver.service: Main process exited, code=exited, status=1/FAILURE
Jan 31 09:39:13 debianbuster systemd[1]: paperless-webserver.service: Failed to kill control group /system.slice/containerd.service/system.slice/paperless-webserver.service, ignoring: Input/output error
Jan 31 09:39:13 debianbuster systemd[1]: paperless-webserver.service: Failed to kill control group /system.slice/containerd.service/system.slice/paperless-webserver.service, ignoring: Input/output error
Jan 31 09:39:13 debianbuster systemd[1]: paperless-webserver.service: Failed to kill control group /system.slice/containerd.service/system.slice/paperless-webserver.service, ignoring: Input/output error
Jan 31 09:39:13 debianbuster systemd[1]: paperless-webserver.service: Failed to kill control group /system.slice/containerd.service/system.slice/paperless-webserver.service, ignoring: Input/output error
Jan 31 09:39:13 debianbuster systemd[1]: paperless-webserver.service: Failed with result 'exit-code'.
```

**Comment by C0nsultant** [comment]
If you're interested in an alternative (possibly simpler) approach:
Pull the relevant information from the `paperless-webserver.service` file that is shipped with a release 
(e.g. regex `^ExecStart=(.+)/bin/gunicorn (.+) -b ([\d+\.]{4}):(\d+)$`)
and then use those values 
(e.g. regex replace `ExecStart={{ paperlessng_virtualenv }}/bin/gunicorn \2 -b {{ paperlessng_listen_address }}:{{ paperlessng_listen_port }}`)
 insteam of duplicating the logic in ansible

**Comment by jonaswinkler** [comment]
> Jan 31 09:39:07 debianbuster gunicorn[12015]: ModuleNotFoundError: No module named 'paperless.asgi'

This is a new module that is only present on this branch.

**Comment by jonaswinkler** [comment]
Actually, let's just use the gunicorn configuration file in these scripts. That will solve these issues. Once all branches have the updates configuration, this won't be an issue anymore anyway.

**Pull request closed without merging**
