### PR TITLE
Add support for rtf

### PR DESCRIPTION
**Pull request by jovandeginste**
Signed-off-by: Jo Vandeginste <Jo.Vandeginste@kuleuven.be>

### CODE REVIEW

**Comment by jovandeginste** [comment]
Yesterday I received my first "official" rtf-document (per mail, FWIW); I wanted no hassle adding it in Paperless!

**Comment by jonaswinkler** [comment]
People still use that? :)

On a side note, do you know if tika / gotenberg is able to handle CSV documents, similar to how they process excel sheets?

**Comment by jovandeginste** [comment]
I'll test it in the near future

**Comment by jovandeginste** [comment]
I'm afraid it doesn't... https://github.com/thecodingmachine/gotenberg/issues/234

**Comment by jovandeginste** [comment]
We may want to work on using unoconv directly...?

**Comment by jonaswinkler** [comment]
`unoconv` pulls in lots of dependencies (libreoffice in particular), so that won't do.

This was just an idea.

**Pull request merged**
