### PR TITLE
Mobile Improvements for "Quick Filters"

### PR DESCRIPTION
**Pull request by shamoon**
@jonaswinkler I know mobile support in general is on the back burner but figured I'd at least improve the quick-filters I worked on (#111). Basically added breakpoints for smaller screens and then buttons become icons (except dates cause I couldn't think of good ones to differentiate them) on mobile screens to fit everything. Curious to see what you think! Screenshots below

Mobile:
Screen Shot 2020-12-14 at 4 19 31 PM

Medium displays:
Screen Shot 2020-12-14 at 4 20 06 PM

Large displays:
Screen Shot 2020-12-14 at 5 19 57 PM

### CODE REVIEW

**Comment by shamoon** [comment]
I messed up merging dev, will figure out where

**Comment by jonaswinkler** [comment]
Well yeah, I'm sorry. I change a couple things.

**Comment by shamoon** [comment]
Ok I will create a new PR

**Comment by shamoon** [comment]
Im currently getting errors in the dev branch? Maybe I'll wait a sec

**Pull request closed without merging**
