### PR TITLE
Ansible - build release archive from source

### PR DESCRIPTION
**Pull request by C0nsultant**
This change makes it possible to install a version of NG that does not (yet) have a release archive.
One thing this enables is actual CI for the ansible role by installing the sources from a PR instead of pulling the previous release archive.

In addition, I switched the default installation target version to "latest".
When this version string is specified, the latest release archive is pulled, making it obsolete to update the version string in the ansible role.

- [x] Verify that all required steps to build the release archive are performed

### CODE REVIEW

**Comment by C0nsultant** [comment]
So I still don't fully understand the packaging process, apparently.
What is `pipenv` used for anymore? 

- I'm skipping [documentation](https://github.com/jonaswinkler/paperless-ng/blob/ng-1.0.0/.github/workflows/ci.yml#L6-L45) and [tests](https://github.com/jonaswinkler/paperless-ng/blob/ng-1.0.0/.github/workflows/ci.yml#L53-L98) as they should not be executed during installation
- [Frontend compilation](https://github.com/jonaswinkler/paperless-ng/blob/ng-1.0.0/.github/workflows/ci.yml#L100-L118) apparently only depends on node, no python required
- [Release packaging](https://github.com/jonaswinkler/paperless-ng/blob/ng-1.0.0/.github/workflows/ci.yml#L120-L183) installs from the static `requirements.txt` (which I guess you update manually, @jonaswinkler)

**Comment by jonaswinkler** [comment]
Note to my self: I should work on the documentation.

* frontend: only node. `ng build --prod` takes care of everything. `compilemessages` is for localization of the back end / django part. (Strings on the admin, and errors returned by the back end, mostly.)
* pipenv / requirements. Pipenv is *really* useful in development, for various reasons. For deployment, I found it was complicating things, especially when building for arm (unclear error messages and long build times due to it not playing nice with piwheels). Therefore, `requirements.txt` is in the repository as well, which I update along with `Pipfile.lock`. You shouldn't need to use the Pipfiles at all.

I don't exactly know how the ansible scripts work; Do you think that the packaging process is too complicated and could / should be simplified?

**Comment by C0nsultant** [comment]
> Do you think that the packaging process is too complicated and could / should be simplified?

After doing this PR: No, it's not too complicated in practice. My mind was playing tricks and made it a much bigger problem that it actually it. The whole story about `pipenv` has changed significantly since I first inquired about it in #304. The process is actually pretty simple, it's just not very clear what is mandatory and what is optional. Reverse-engeneering a github actions YAML for this is fine to me...

> I should work on the documentation.

... but you appear to smell somthing there :wink:.

> frontend only node... compilemessages for the back end

Thanks for clarifying!

> Pipenv is really useful in development

I have given it many trials, including my own projects and commercial ones. The idea behind it is a thing of beauty. It's just that it has caused more problems that it was worth when it was scaled to more than one person. every. single. time. Cool to see you could integrate it into your dev workflow successfully :) Also somewhat happy you're not deploying with it :)

> You shouldn't need to use the Pipfiles at all.

Thanks, so this role will rely on the `requirements.txt`, then.

> I don't exactly know how the ansible scripts work

`ansible/tasks/install-source.yml` is the one that build a release archive for arbitrary versions (well anything past 0.9.13, really. The process has changed so much, I don't see a benefit in investing the time to support old releases). It basically does what the github actions do:

- pull the source (at whatever git-commit is behind the `paperlessng_version`, be it branch/tag/commit/ref)
- compile the frontend
- copy whatever needs to be copied into a `dist/`
- `compilemessages`
- `collectstatic`
- for compatability with the rest of the script, everything is packaged up and extracted to the same location the official release would be extracted to (seems redundant now that it is written out... I should just move the files)

**Comment by C0nsultant** [comment]
Github actions have annoyingly *secure* permissions set on `/tmp`... Will have to find a workaround for that.

**Comment by jonaswinkler** [comment]
Molecule creates temporary users, and the home directories of these users end up in `/tmp`; However, binary files installed from python dependencies also end up there, and a missing +x flag prevends execution, causing this error. Correct?

**Comment by C0nsultant** [comment]
You're very close. The symptom is correct: `/tmp` and contents do not have `x`, even for root. The reason is a little different: molecule uses docker containers to achieve isolation and reproducibility (though there are also different [drivers](https://molecule.readthedocs.io/en/latest/configuration.html#driver), e.g. local and ssh).

To get docker working with this ansible role, I had to jump through a somewhat large hoop: The role relies on systemd, which docker generally does not have. There are systemd-aware and -enabled containers (e.g. [jrei/systemd-ubuntu](https://hub.docker.com/r/jrei/systemd-ubuntu)), but they require mapping though certain [host paths](https://github.com/jonaswinkler/paperless-ng/blob/ng-1.0.0/ansible/molecule/fresh/molecule.yml#L13-15) to work properly. Among those paths is `/tmp`. And from all I can tell, GitHub runners actually have `umask`ed the executable bits on (at least) `/tmp`.

Two workarounds that come to mind:
- Try to run the molecule tests without mapping the host `/tmp`. This does not solve the problem in general as I'm sure more systems are running with similarly strict permissions.
- Do not use `/tmp` (well, ansible [tempfile](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/tempfile_module.html) really, which uses `/tmp` by default) and instead place the temporary directories inside `paperlessng_directory`.

**Comment by C0nsultant** [comment]
When testing the installation built from source with this role, uploading a `.txt` currently results in

> Detected mime type: inode/x-empty

Have you seen this before, @jonaswinkler? At first I presumed there was a mime-lib missing, but `mime-support` is installed.

**Comment by jonaswinkler** [comment]
Might be an issue with older or different versions of `file` and `libmagic`. The versions on debian stable have some issues with certain PDF files and report application/octet-steam instead of the correct type. This might be the issue here as well. Solution for the docker image was to install these dependencies from bullseye, but I don't think you want to do this with a bare metal / ansible install.

**Comment by C0nsultant** [comment]
The thing that makes me thinks it GH actions is that I ran the molecule tests on two separate systems and there are no `inode/x-empty` errors.
I just stumbled across [PAPERLESS_CONVERT_TMPDIR](https://paperless-ng.readthedocs.io/en/latest/configuration.html?highlight=tmp#software-tweaks):

> Similar to the memory limit, if you’ve got a small system and your OS mounts /tmp as tmpfs, you should set this to a path that’s on a physical disk, like /home/your_user/tmp or something. 

This is the only reference to `tmp` in the docs, but I'm not sure that is part of the problem. I would assume conversion only happens after mime type is determined?

**Comment by jonaswinkler** [comment]
* Is the text file empty by any chance?

Regarding PAPERLESS_CONVERT_TMPDIR: This has been introduced in original paperless, I don't know the excact reasoning behind this. The only place where this is used now is during thumbnail generation (that part calls `convert` directly). Paperless used to call `convert` to convert PDF documents to a series of images for OCR, but that's all handled by OCRmyPDF now. Might have been related to this.

**Comment by C0nsultant** [comment]
Well there we go. For this usecase, mapping the mentioned directories as `tmpfs` is not essential. Not doing so also solves the problem.
From my side, this is ready to be merged.

>    Is the text file empty by any chance?

It contains 64 random ASCII characters.

Thanks for the background on `PAPERLESS_CONVERT_TMPDIR`, it most definitely then is not the problem.
On the other hand, I honstely don't know which component fails when the `tmpfs` are mounted. There are only two log lines regarding the failed runs. Maybe you can make some sense of them:

> [2021-01-27T07:41:53.401389+01:00] Consuming yFgVcnVq.txt
  [2021-01-27T07:41:53.405161+01:00] Detected mime type: inode/x-empty

**Comment by C0nsultant** [comment]
Well since this originates in [`magic.from_file()`](https://github.com/jonaswinkler/paperless-ng/blob/master/src/documents/consumer.py#L146), I would assume it is related to [python-magic](https://github.com/ahupp/python-magic) or the underlying `libmagic` (and by extension `file`). I'll try to figure out what breaks when I there is some time.

**Comment by jonaswinkler** [comment]
> It contains 64 random ASCII characters.

Did some research and `inode/x-empty` is reported for empty files. And `file --mime-type text.txt` with test.txt empty does exactly that over here. Maybe an issue with how you generate that random text file?

**Comment by C0nsultant** [comment]
A wild guess here: Python's [`f.write()`](https://github.com/C0nsultant/paperless-ng/blob/ansible-fromsource/src/documents/views.py#L385) does **not** guarantee the contents to be written (see Python [docs](https://docs.python.org/3/tutorial/inputoutput.html#reading-and-writing-files)) to the file when the handle is still open:
> Warning
Calling f.write() without using the with keyword or calling f.close() might result in the arguments of f.write() not being completely written to the disk, even if the program exits successfully.

**Comment by jonaswinkler** [comment]
Ouch. If that's the issue, good spot, and I'm sorry.

**Comment by C0nsultant** [comment]
Well for any document other than my contrived 64 Byte .txt, this would not have caused any problems.
Still, this is a race condition in production code. `f.flush()` solves it, though. :)

Now this is _really_ ready to merge.

**Comment by jonaswinkler** [comment]
alright, lets hope this works.

**Pull request merged**
