### PR TITLE
Encourage Discussion Ideas instead of Issues for [Feature Requests]

### PR DESCRIPTION
**Pull request by shamoon**
This PR was discussed in https://github.com/jonaswinkler/paperless-ng/issues/402#issuecomment-770409696 it adds:

- Redirects users to use Discussions in Ideas category in the readme, as well as in new issue templates. It also removes the FR issue template.
- ~~Adds a "suggest an idea" icon to the app next to GH link~~ Edit: moved to separate PR

Also I found this which sounds like it would be useful since a lot of the "issues" in the repo right now are actually feature requests: https://docs.github.com/en/discussions/managing-discussions-for-your-community/managing-discussions-in-your-repository#converting-issues-based-on-labels

### CODE REVIEW

**Comment by jonaswinkler** [comment]
Hold on a second, let me rename that discussion section to "feature requests". That's more Links will probably change.

Also, documentation and readme changes can go straight into master, so that they're immediately visible.

The info section looks good, PR as is to dev.

**Comment by shamoon** [comment]
OK I'll separate out the PRs and update the links in documentation.

**Comment by shamoon** [comment]
Ah, the thing about changing this to go into `master` is that it was based on `dev` which means it has all that in it. Would you rather I create a new PR for this or just change it to merge into dev?

**Comment by jonaswinkler** [comment]
> Would you rather I create a new PR for this or just change it to merge into dev?

Up to you. If you want these changes to appear immediately, make a new PR. IF not, let me know, and they'll go into dev and eventually into master.

**Comment by shamoon** [comment]
Assuming the next release isnt ages away I think we can just merge this into dev, especially since we discovered that you can move old issues to discussions if you want to.

**Comment by shamoon** [comment]
Ps. I think you should remove the “Other” issue template too, sorry I probably should have included that in this PR.

And out of curiosity are you planning to convert the FR issues into discussions? Just curious for other repos of mine how that works out

**Pull request merged**
