### PR TITLE
Bulk editing UI

### PR DESCRIPTION
**Pull request by shamoon**
This PR addresses #60 and #170 and includes:

- New UI that replaces filter editor when entering bulk edit "mode", updates check mark
- Shows  – / ✓ for tags/correspondents/doc types according to how many items in the selected set have that item assigned and allows toggling of those assignments directly from menu
- Badge counts are updated in real time when editing
- Lots of refactoring

TODO:

- [ ] Add API support for bulk assigning multiple tags (see [`document-list.component.ts` line 187](https://github.com/jonaswinkler/paperless-ng/pull/162/files#diff-cab8e3664da267285e26bc2320dc8245f6f254e03125f35993b027b7a0636036R187))
- [ ] Test with an actual backend that has bulk editing working 😅!

bulk-editor-400da7b-3-2

### CODE REVIEW

**Comment by jonaswinkler** [comment]
Oh well, this is really messed up, I'd wish you'd pushed that to the bulk editing branch. I guess that can't be changed now. I'll look into this soon.

**Comment by shamoon** [comment]
What’s messed up? I merged dev into this, I can make a new PR into `bulk-edit` if it’s really a problem?

**Comment by shamoon** [comment]
Sorry, what’s messed up? 

I merged dev into this and it works fine in my testing but if it’s a problem I think can just revert the merge of `dev` and change this PR into `bulk-edit` if you prefer?

**Review by shamoon — COMMENTED** [review]
I committed a couple testing files that I removed, otherwise this builds & runs OK for me. As I said, let me know if you want me to revert `dev` merge and change this PR to go into `feature-bulk-edit`

**Comment by jonaswinkler** [comment]
No, its alright.

**Comment by jonaswinkler** [comment]
I'm getting some serious performance issues with this, the UI seems to freeze for a couple seconds after applying operations. Have to look into that further.

**Comment by shamoon** [comment]
Hmm, I wonder if its something more systemic but I pushed a change to use `ngIf` for the editor components instead of just hiding them, perhaps that will help?

**Comment by shamoon** [comment]
Hmm, I didn’t notice that.

I wonder if its something more systemic but I pushed a change to use `ngIf` for the editor components instead of just hiding them, perhaps that will help?

**Comment by shamoon** [comment]
Oh maybe that’s because I wasn’t actually testing with a backend that performs the operations. Anyway let me know if I can help.

**Comment by jonaswinkler** [comment]
Seems better now!

**Comment by shamoon** [comment]
Cool. I have some other ideas on how to improve but I'll wait until after this is merged.

**Comment by jonaswinkler** [comment]
- When selecting documents on multiple pages, I seem to be unable to remove a tag that does not appear on documents on the current page (but does appear on selected documents on other pages). I'm still not convinced that this works with multiple pages at all.
- Actually, when documents are selected on multiple pages, I seem to be unable to remove tags at all.
- Please merge this into the feature-bulk-edit branch. This needs quite a bit more work. I'm also considering to release the current state of the bulk editing capabilities and have the nice interface added later.

**Comment by shamoon** [comment]
OK, so you helped me see a big flaw in my logic before but I think I've fixed this.

1. I changed the base branch to `bulk-edit`
2. I rewrote the way toggling is passed from the bulk editor and change detection is much simpler & faster now (much fewer array operations). So removal is fixed, all add/remove should work as intended.
3. When items are selected across pages I added a "Remove all" button to the dropdown. Again that is because with selections across pages we dont get –/✓ so we need another way to remove.
4. One case we didn't discuss is since tags allow multiple you can create an action where youre adding and removing tags at the same time. It works well UI-wise, I think, to remove you toggle _off_ some tags that are – and to add ✓ others. At the moment the UI shows one dialog but then just calls two API operations (both of which I think still need to be implemented). I think its cool to be able to do this and useful (e.g. "remove **Inbox** tag and add **SomeTag**" to all items very easily)

As you can tell I want to sort this out as I've put a fair amount of work into it so let me know your thoughts and if there are any issues with it that I can address. Thanks for your patience.

**Comment by jonaswinkler** [comment]
> * I changed the base branch to `bulk-edit`

Thank you!

> * When items are selected across pages I added a "Remove all" button to the dropdown. Again that is because with selections across pages we dont get –/✓ so we need another way to remove.

I'll see how that works. I've got some ideas on how to modify the selection model that we actually get this information for all selected documents across multiple pages.

> * One case we didn't discuss is since tags allow multiple you can create an action where youre adding and removing tags at the same time. It works well UI-wise, I think, to remove you toggle _off_ some tags that are – and to add ✓ others. At the moment the UI shows one dialog but then just calls two API operations (both of which I think still need to be implemented). I think its cool to be able to do this and useful (e.g. "remove **Inbox** tag and add **SomeTag**" to all items very easily)

So, we'll essentially need an API operation `modify_tags` that both adds and removes tags at the same time. Doing two API calls in a row isn't all that good, since these bulk operations also cause paperless to potentially rename all affected documents (`PAPERLESS_FILENAME_FORMAT`). I made sure that this won't cause any issues, but its unnecessary workload on the backend nonetheless.

> As you can tell I want to sort this out as I've put a fair amount of work into it so let me know your thoughts and if there are any issues with it that I can address. Thanks for your patience.

Please don't get me wrong. I really appreciate your contributions. It's just that I want to make sure they work for all edge cases and that the code is reasonably clean.

**Comment by shamoon** [comment]
Sounds good about condensing the API operation, I assumed you'd want to do that.

> Please don't get me wrong. I really appreciate your contributions. It's just that I want to make sure they work for all edge cases and that the code is reasonably clean.

Oh thanks for saying that—yes I want to make sure of all that too, I just meant that I was committed to making it work! Let me know if / when you have change suggestions.

**Comment by jonaswinkler** [comment]
Alright, I've had a pretty good look at the source now.

- I'll modify the current selection logic in the list service / maybe create a separate selection service that manages selection state and keeps track of what tags / correspondents / types are selected / partially selected / not selected at all. With that, the bulk editor does not have to do any logic regarding that at all, except for calling the service and asking what's up.
- Need to do some refactoring on the components, the interface of the bulk-editor can be simplified quite a bit... no need to for events when we can simply move these into the bulk editor... also the bulk editor should simply get the document list service as well instead of managing its own selection set and document list, the bidirectional binding on these two things could be the cause for the performance issues I'm getting.

The interface already feels very nice to use, kudos. With that, I almost feel that there's almost no need anymore for editing this stuff on the document detail page, this is much faster. Also really like the reuse of the drop down menus.

I'll take it from here, but not until after Christmas :)

**Comment by shamoon** [comment]
> * I'll modify the current selection logic in the list service / maybe create a separate selection service that manages selection state and keeps track of what tags / correspondents / types are selected / partially selected / not selected at all. With that, the bulk editor does not have to do any logic regarding that at all, except for calling the service and asking what's up.

Sure though since it seemed to me like the filter editor where we'd keep the logic in the component since its not really going to be used elsewhere. Are you considering adding API stuff to get this info?

> * Need to do some refactoring on the components, the interface of the bulk-editor can be simplified quite a bit... no need to for events for the bulk edit functions when we can simply move these into the bulk editor... also the bulk editor should simply get the document list service as well instead of managing its own selection set and document list, the bidirectional binding on these two things could be the cause for the performance issues I'm getting.

Makes sense

> The interface already feels very nice to use, kudos. With that, I almost feel that there's almost no need anymore for editing this stuff on the document detail page, this is much faster. Also really like the reuse of the drop down menus.
> 
> I'll take it from here, but not until after Christmas :)

Glad you like it! I think you should keep the document detail page even if this is quicker but maybe you didn't really mean you were considering getting rid of that.

I would be happy to try and tackle the above stuff (well API side is your end) but of course if you'd prefer to take it I defer to you.

**Comment by jonaswinkler** [comment]
> Sure though since it seemed to me like the filter editor where we'd keep the logic in the component since its not really going to be used elsewhere. Are you considering adding API stuff to get this info?

Probably.

**Pull request merged**
