### PR TITLE
Updates to sidebar "Misc" section

### PR DESCRIPTION
**Pull request by shamoon**
This PR moves the "misc" section of the sidebar and renames it to "info" and updates its contents, see:

106400838-cb9a4100-63d5-11eb-9df3-3216844b1942

### CODE REVIEW

**Comment by jonaswinkler** [comment]
Can't test right now. How about scrolling with lots of saved views and opened documents?

**Comment by shamoon** [comment]
That section just gets pushed down, like one would expect I think. It uses CSS flexbox so only takes up space if its there. See video with a lot of docs, then I close them

https://user-images.githubusercontent.com/4887959/106403795-2be4af00-63e5-11eb-8bf7-c5ddafe530d3.mov

**Comment by shamoon** [comment]
Let me fix a couple small CSS bugs

**Comment by shamoon** [comment]
Okey dokey =)

**Comment by jonaswinkler** [comment]
Just a minor nitpick when the menu gets very small

image

**Comment by shamoon** [comment]
Looks like when the window is very narrow (e.g. left to right) not short, yea? I mean one thing would be to set `white-space: nowrap;` on the Github button, then we could perhaps add some classes to hide the text of 'suggest an idea' depending on screen size. Want a PR for this or nah?

**Comment by jonaswinkler** [comment]
I think it would be best to put the "Suggest an idea" link on a new line, if too small. (On a side note, some translations are quite a bit longer)

**Comment by shamoon** [comment]
Yea true. See this: https://github.com/jonaswinkler/paperless-ng/commit/53265ece4ae501e28f45d004977800dfcf8ab8a0

Can submit as PR obviously if you want, LMK

**Comment by jonaswinkler** [comment]
Thank you!

**Pull request merged**
