### PR TITLE
Additional / organized card info

### PR DESCRIPTION
**Pull request by shamoon**
This PR addresses #423 and #439 and adds / organizes info on cards (ASN, doc type). Screenshots below. Highlights:

- Document type (if set) is displayed without tooltip
- Doc type is clickable for quick filtering
- Date created & ASN (if set) are also shown in similar organized manner
- Overall height of small cards only varies +/- 10% depending on the number of items shown, so still works well on narrow (mobile) screen sizes
- Larger action buttons on small cards
- Nice & neat =)

Of course, please let me know if I missed any issues

Screen Shot 2021-03-12 at 8 13 00 AM

Screen Shot 2021-03-12 at 9 20 59 AM

### CODE REVIEW

**Comment by jonaswinkler** [comment]
image

How about fitting Date and ASN on one line? ASN right-aligned, if available. Space is available, and ASNs should not have 10+ digits anyway.

**Comment by shamoon** [comment]
Yea great! In my test install I made ASNs too long (clearly I don’t actually use them). I can update this later tonight.

**Comment by shamoon** [comment]
Cool, updated. I think it looks slightly less 'neat' but I like that it makes it more compact, happy with the trade-off. If the ASN doesnt fit it will gracefully show it above like before (see screenshot with short ASN and long ASN, same when card gets too narrow).

Screen Shot 2021-03-12 at 7 59 00 PM

**Comment by sbrunner** [comment]
Nice, thanks :-)

**Pull request merged**
