### PR TITLE
Add LDAP auth support

### PR DESCRIPTION
**Pull request by dani**
I needed LDAP auth to use paperless (which I'm evaluating as a personal document management system), so, I've hacked it. It's pretty basic, only support users (not groups or fancy searches) but should fit most needs. Tested against a samba4 (AD style) directory only, but should work with most directories

### CODE REVIEW

**Comment by jonaswinkler** [comment]
Please rebase this on the `dev` branch.

**Comment by jonaswinkler** [comment]
* Also, some dependencies are missing for the build, apparently some header files required to build the python wheel.
* paperless ng uses Pipenv. Please install packages with "pipenv install <package> --keep-outdated" and then generate the requirements.txt with "pipenv lock -r > requirements.txt".

**Comment by dani** [comment]
OK, I'll try to update the PR as soon as I have some spare time :-)

**Comment by tfmm** [comment]
@dani I looked at the build log, and it appears that the ldap development packages need to be added to the apt package install list.  I would try adding these, and see if the build then completes. 

```
libsasl2-dev
python-dev
libldap2-dev
libssl-dev
```

**Comment by dani** [comment]
But where's this list defined ? Is it the one in the Dockerfile or elsewhere ?

**Comment by tfmm** [comment]
The portion of the build that's failing appears to be docker, so yes, it should be the list in the Dockerfile.

**Comment by dani** [comment]
Looks like it's still failing on the lber.h (which should be installed with libldap2-dev)...

**Comment by andretheolauret** [comment]
Hello I use paperless-ng and want to integrate it in app catalog of the project YunoHost, but for better support they require to have LDAP support. Can this PR be more under development please

**Comment by dani** [comment]
I'd like to go foward but I really have no idea why is the test build failing.

**Comment by andretheolauret** [comment]
> I'd like to go foward but I really have no idea why is the test build failing.

I think it’s because you need this
sudo apt-get install libldap2-dev

**Comment by andretheolauret** [comment]
> > I'd like to go foward but I really have no idea why is the test build failing.
> 
> I think it’s because you need this
> sudo apt-get install libldap2-dev

Are you sure the CI have this ?

**Comment by andretheolauret** [comment]
Here you can find some answer 
https://stackoverflow.com/questions/4768446/i-cant-install-python-ldap

**Comment by dani** [comment]
Well, I've added the dependencies in the Dockerfile. If they have to be specified somewhere else, I have no idea where

**Comment by andretheolauret** [comment]
I dont see Also error with, so i think you should mention project maintainer may he will can help you better

**Comment by TheFehr** [comment]
@dani in the .github/workflows/ci.yaml directory you'll probably need to add the dependencies as well

**Comment by dani** [comment]
Looks like the build is now successful. Only the test coverage slightly decreased. Is this enough for the PR to be merged ?

**Comment by maxulm** [comment]
Would be great having this feature :)

**Comment by telvgehc** [comment]
Update?

**Comment by hydrian** [comment]
Yea... Waiting on this before I can do a rollout of it to my family...

**Comment by Marook332** [comment]
I would love to test this feature :)

**Pull request closed without merging**
